POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "zxh",
  "idCard": "123",
  "type": "3"
}

###
GET http://localhost:8000/member/passenger/query-list?page=1&size=2
Accept: application/json
token: {{token}}

###